services:
  db:
    image: mysql:latest
    container_name: mytheresa_db
    environment:
      MYSQL_DATABASE: mytheresa
      MYSQL_USER: mytheresa
      MYSQL_PASSWORD: mytheresa
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3325:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mytheresa  
    environment:
      DB_USER: mytheresa
      DB_PASSWORD: mytheresa
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mytheresa
    ports:
      - "8080:8080"  
    depends_on:
      db:
        condition: service_healthy
  test:
      build: .   
      container_name: mytheresa_test   
      environment:
        DB_USER: mytheresa
        DB_PASSWORD: mytheresa
        DB_HOST: db
        DB_PORT: 3306
        DB_NAME: mytheresa
      depends_on:
        db:
          condition: service_healthy
      command: ["go", "test", "./test"]